#!/bin/bash
#
#  generate_secrets.sh
#  PdfExpert
#
#  Invoked by the "Generate Secrets" build phase, BEFORE Compile Sources.
#
#  Reads the git-ignored ProjectInfo.plist and emits
#  pdfexpert/Generated/ObfuscatedSecrets.swift with the API keys stored as bytes
#  XOR-ed against a FRESH RANDOM pad generated on every build. Consequences:
#    * the cleartext key is never bundled into the IPA, and
#    * because the pad changes each build, no stable recognizable string exists in
#      the binary, so `strings` on the product reveals nothing.
#  A missing plist or missing key degrades to an empty secret (build warning, no
#  failure) so the app still compiles without a populated ProjectInfo.plist.
#
set -euo pipefail

# When run from Xcode, SRCROOT is set. Fall back to the repo root for manual runs.
SRCROOT="${SRCROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"

PLIST="${SRCROOT}/pdfexpert/Resources/ProjectInfo.plist"
OUT_FILE="${SRCROOT}/pdfexpert/Generated/ObfuscatedSecrets.swift"

mkdir -p "$(dirname "${OUT_FILE}")"

/usr/bin/env python3 - "${PLIST}" "${OUT_FILE}" <<'PY'
import os
import sys
import plistlib

plist_path, out_path = sys.argv[1], sys.argv[2]

data = {}
if os.path.isfile(plist_path):
    try:
        with open(plist_path, "rb") as handle:
            loaded = plistlib.load(handle)
            if isinstance(loaded, dict):
                data = loaded
            else:
                print(f"warning: {plist_path} is not a dictionary — secrets will be empty", file=sys.stderr)
    except Exception as exc:  # noqa: BLE001
        print(f"warning: could not parse {plist_path} ({exc}) — secrets will be empty", file=sys.stderr)
else:
    print(f"warning: ProjectInfo.plist not found at {plist_path} — secrets will be empty", file=sys.stderr)

# (Swift property name, plist key)
KEYS = [
    ("appleAttributionApiKey", "APPLE_ATTRIBUTION_API_KEY"),
]


def _format(byte_values):
    if not byte_values:
        return "[]"
    return "[" + ", ".join(f"0x{value:02x}" for value in byte_values) + "]"


def obfuscated_line(swift_name, plist_key):
    if plist_key not in data:
        print(f"warning: {plist_key} missing from ProjectInfo.plist — secret will be empty", file=sys.stderr)
    raw = data.get(plist_key, "")
    if raw is None:
        raw = ""
    secret_bytes = str(raw).encode("utf-8")
    pad = os.urandom(len(secret_bytes))
    obfuscated = bytes(secret ^ mask for secret, mask in zip(secret_bytes, pad))
    return f"    static let {swift_name} = ObfuscatedSecret(pad: {_format(pad)}, bytes: {_format(obfuscated)})"


lines = [obfuscated_line(name, key) for name, key in KEYS]

content = (
    "// Auto-generated by the \"Generate Secrets\" build phase. DO NOT EDIT. Git-ignored.\n"
    "// Regenerated on every build with a fresh random XOR pad, so the binary carries\n"
    "// no stable representation of any secret.\n"
    "enum ObfuscatedSecrets {\n"
    + "\n".join(lines)
    + "\n}\n"
)

with open(out_path, "w") as handle:
    handle.write(content)
PY

echo "Generate Secrets: wrote ${OUT_FILE}"
